
package wspack;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerImpService", targetNamespace = "http://mypack/", wsdlLocation = "http://localhost:7779/ws/hello?wsdl")
public class ServerImpService
    extends Service
{

    private final static URL SERVERIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERIMPSERVICE_EXCEPTION;
    private final static QName SERVERIMPSERVICE_QNAME = new QName("http://mypack/", "ServerImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7779/ws/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERIMPSERVICE_WSDL_LOCATION = url;
        SERVERIMPSERVICE_EXCEPTION = e;
    }

    public ServerImpService() {
        super(__getWsdlLocation(), SERVERIMPSERVICE_QNAME);
    }

    public ServerImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERIMPSERVICE_QNAME, features);
    }

    public ServerImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVERIMPSERVICE_QNAME);
    }

    public ServerImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERIMPSERVICE_QNAME, features);
    }

    public ServerImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerImp
     */
    @WebEndpoint(name = "ServerImpPort")
    public ServerImp getServerImpPort() {
        return super.getPort(new QName("http://mypack/", "ServerImpPort"), ServerImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerImp
     */
    @WebEndpoint(name = "ServerImpPort")
    public ServerImp getServerImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mypack/", "ServerImpPort"), ServerImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERIMPSERVICE_EXCEPTION!= null) {
            throw SERVERIMPSERVICE_EXCEPTION;
        }
        return SERVERIMPSERVICE_WSDL_LOCATION;
    }

}
